[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/qurating", "src/qurating/prompting/templates/*.txt"]

[tool.uv.sources]
fabdata-llm = { git = "https://github.com/AI-for-Education/fabdata-llm.git", rev = "main" }

[tool.uv.extra-build-dependencies]
flash-attn = ["torch"]

[project]
name = "fab-qurating"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "anthropic>=0.49.0",
    "datasets>=4.0.0",
    "fabdata-llm==0.28.1",
    "joblib>=1.5.1",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "openai",
    "peft>=0.17.1",
    "pydantic>=2.11.7",
    "tiktoken",
    "tqdm>=4.67.1",
    "transformers>=4.54.0",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
]


[dependency-groups]
dev = [
    "dvc>=3.61.0",
    "dvc-azure>=3.1.0",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
]

[tool.uv]
no-build-isolation-package = ['flash-attn']
